POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer 1q2w3e4r5t6y7


{
    "title": "New post2",
    "author": "A.Kivinen",
    "url": "www.blogis.fi",
    "likes": 0

}
